server:
  port: 8080
spring:
  application:
    group: consumo
    kafka: localhost:9092
    definition: sendCashIn;sendCashOut
    mongo: mongodb://root:rootpassword@localhost
  data:
    mongodb:
      auto-index-creation: true
      database: app_cash_flow
      authentication-database: admin
      uri: ${spring.application.mongo}
      repositories:
        enabled: true
  cloud:
    stream:
      default:
        consumer:
          maxAttempts: 5000
          concurrency: 100
      function:
        definition: ${spring.application.definition}
      kafka:
        default:
          producer:
            configuration:
              acks: all
              retries: 2147483647
              enable.idempotence: true
            sync: true
          consumer:
            configuration:
              max.poll.records: 1
        binder:
          configuration:
            isolation:
              level: read_committed
          autoCreateTopics: false
          brokers: ${spring.application.kafka}
      bindings:
        sendCashIn-out-0:
          destination:  cashflow-sendCashIn
          group: ${spring.application.group}
          content-type: application/json
        sendCashOut-out-0:
          destination: cashflow-sendCashOut
          group: ${spring.application.group}
          content-type: application/json

systemProp:
  sonar:
    projectKey: teste
    host:
      url: http://localhost:9000